### ISSUE TITLE
Relocating virtualenv with pyc files fails

### ISSUE THREAD

**Issue by brejoc** [Yelp/virtualenv-tools#10]
I've noticed today, that our build pipelines failed with minor changes. I could track this down to the virtualenv relocation. Any ideas why this is happening?

### Steps to reproduce

1. Create a virtualenv that includes .pyc files
2. Try to relocate the virtualenv like this: `virtualenv-tools --update-path /usr/local/foo`

The relocation fails with the following error:

```
$ virtualenv-tools --update-path /usr/local/foo
Error in ./lib/python3.4/site-packages/zope/interface/__pycache__/__init__.cpython-34.pyc
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv-tools", line 9, in <module>
    load_entry_point('virtualenv-tools==1.0-yelp4', 'console_scripts', 'virtualenv-tools')()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_tools.py", line 316, in main
    update_paths(venv, update_path)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_tools.py", line 211, in update_paths
    update_pycs(venv.lib_dir, new_path)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_tools.py", line 167, in update_pycs
    update_pyc(filename, local_path)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_tools.py", line 114, in update_pyc
    code = marshal.load(f)
ValueError: bad marshal data (string ref out of range)
```
### Workaround
As a work-around, the .pyc files can be deleted with `find . -name '*.pyc' -delete`. After that the relocation succeeds.

**Comment by chriskuehl** [comment]
It looks like you're trying to relocate a python3.4 virtualenv using a python2.7 installation of virtualenv-tools. Is that right?

I think you have to use the same version of Python (afaik the problem is basically that python2.7 doesn't understand python3.4 pyc files).

**Comment by asottile** [comment]
Yep, the interpreter version needs to be the same between the virtualenv and virtualenv-tools.

**Comment by brejoc** [comment]
Thanks, you are right. Seems like I've somehow mixed Python versions in the build pipeline and didn't notice. Sorry!
