### ISSUE TITLE
Unable to find the VIRTUAL_ENV variable in activate.sh for recent virtualenv versions.

### ISSUE THREAD

**Issue by kwvanderlinde** [Yelp/virtualenv-tools#21]
Starting in `virtualenv==20.0.0`, the `VIRTUAL_ENV` variable is now defined using single quotes instead of double quotes. This breaks `virtualenv-tools3` as it specifically searches for the string `VIRTUAL_ENV="` in `activate.sh`.

**Comment by asottile** [comment]
could you try out the patch in #22?

**Comment by joroscoSF** [comment]
I ran across this same problem yesterday and just stumbled on this issue.  I confirm that this patch fixes the virtualenv upgrade changes.

💯

**Comment by asottile** [comment]
cool -- I'm fixing that problem as well as this upstream: pypa/virtualenv#1596 and then we should be able to release this
