### ISSUE TITLE
virtualenv-tools does not skip PYCs compiled by other Python versions

### ISSUE THREAD

**Issue by jkugler** [Yelp/virtualenv-tools#29]
Some wheels from Pypi come with PYC files created by a version of Python other than the one you're using to create your virtualenv. This causes virtualenv-tools to fail, instead of skipping the "other version" pyc files.

Expected behavior: virtualenv-tools should skip pyc files which are not created by the Python version running virtualenv-tools.

Test case:
```
mkdir project
cd project
python3.11 -m venv .venv
. .venv/bin/activate
pip3 install prometheus_client
deactivate
cd ..
cp -avr project/.venv/ deploy/
cd deploy
virtualenv-tools --update-path $(realpath .)

```
Fails with:
```
Error in ./lib/python3.11/site-packages/prometheus_client/__pycache__/parser.cpython-310.pyc
Traceback (most recent call last):
  File "/home/jkugler/.local/bin/virtualenv-tools", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jkugler/.local/lib/python3.11/site-packages/virtualenv_tools.py", line 358, in main
    update_paths(venv, update_path)
  File "/home/jkugler/.local/lib/python3.11/site-packages/virtualenv_tools.py", line 230, in update_paths
    update_pycs(lib_dir, new_path)
  File "/home/jkugler/.local/lib/python3.11/site-packages/virtualenv_tools.py", line 180, in update_pycs
    update_pyc(filename, local_path)
  File "/home/jkugler/.local/lib/python3.11/site-packages/virtualenv_tools.py", line 122, in update_pyc
    code = marshal.load(f)
           ^^^^^^^^^^^^^^^
ValueError: bad marshal data (unknown type code)
```

**Comment by asottile** [comment]
wheels should not contain pyc files -- this is not a bug in virtualenv-tools but in whoever created that incorrect wheel

I'd recommend manually deleting those files and filing a bug with that project instead

**Comment by jkugler** [comment]
Reading over the PEP (https://peps.python.org/pep-0427/) I found:
>Wheel, being an installation format that is intended to work across multiple versions of Python, does not generally include .pyc files.

and

> Wheel archives do not need to include .pyc and are less tied to a specific Python version or implementation.

So, in neither case does it prohibit (shall not, should not, etc.) but just says it doesn't need to. I've certainly seen it in more than one case.

Would you accept a PR to add the ability to skip "other version" pyc files?

**Comment by jkugler** [comment]
Also, virtualenv-tools is being invoked inside another build tool (in this case, https://github.com/jordansissel/fpm). I don't have the ability to delete the spurious pyc files before it runs the command.  I'll have to experiment.

**Comment by asottile** [comment]
wheels with pyc files are wrong. we should not implement what you're asking especially because it would hide a mistake of relocating with the wrong python

please report the bug to the actual buggy project
