### ISSUE TITLE
Publish package

### ISSUE THREAD

**Issue by brejoc** [Yelp/virtualenv-tools#9]
Looks like the [official project is abandoned](https://github.com/fireteam/virtualenv-tools/issues/11) and this ist the most active fork with Python3 support. Would you be willing to publish this package in the cheeseshop to make it more visible and the installation more convenient? Right now it needs a certain amount of GitHub digging to find this project.

**Comment by asottile** [comment]
I'd be happy to upload to pypi (had to look up the cheese shop reference lol). I think that unfortunately means renaming unless there's some sort of protocol for taking over dead names on pypi? (I guess we could reach out to the original maintainer as well)

**Comment by brejoc** [comment]
I guess trying to reach out to to the Fireteam would be beste. Perhaps they would be happy to see some helping hands. Usually it is not possible to overtake a dead project name on pypi. Even Guido had a hard time convincing the pypi people to free a project name that was dead for five years.

If nothing works, `py3-virtualenv-tools` would not be worst name. `virtualenv-tools` is currently only Python2 and your fork also works with Python3. As more projects are moving on to Python3, more people will bump into this problem.

**Comment by brejoc** [comment]
@asottile Looks like the Fireteam has disappeared. :(

**Comment by bukzor** [comment]
@brejoc @asottile Thoughts on naming a fork?  `yelp-virtualenv-tools` is the most obvious choice, but I don't like it much.

**Comment by asottile** [comment]
`virtualenv-tools3` might be more appropriate?

**Comment by brejoc** [comment]
I'd say the number 3 should definitely be included, since Python3 support is one of the strongest arguments for this fork. `virtualenv-tools3` and `py3-virtualenv-tools` are names that make that quite clear. More and more people will soon be ~forced~convinced  to finally switch and they will bump into the same problem. As soon as they are starting to query the cheese shop, they'll also see this name and immediately know that it is Python3 ready. Marketing through naming. ;D

**Comment by bukzor** [comment]
virtualenv-tools3 is the best of these IMO.

shipit?

**Comment by asottile** [comment]
:boat: :ship: :it:

**Comment by brejoc** [comment]
:shipit: :+1:

**Comment by chriskuehl** [comment]
Sounds great, I'll do this.

**Comment by chriskuehl** [comment]
It's published on PyPI as `virtualenv-tools3`: https://pypi.python.org/pypi/virtualenv-tools3

Thanks for filing this issue!
